CREATE TABLE [dbo].[Carrier_Conveyor](
	[Conveyor_ID] [int] IDENTITY(1,1) NOT NULL,
	[Conveyor_PlantID] [nvarchar](50) NULL,
	[Conveyor_Start_Part_ID] [int] NULL,
	[Conveyor_End_Part_ID] [int] NULL,
	[Conveyor_Description] [nvarchar](max) NULL,
	[Conveyor_Size_Width] [int] NULL,
	[Conveyor_Size_Length] [int] NULL,
	[Conveyor_Size_Height] [int] NULL,
	[Conveyor_Size_Volume_Total_MM2] [int] NULL,
	[Conveyor_Size_Volume_SQM] [int] NULL,
	[Conveyor_Weight_Net] [decimal](18, 0) NULL,
	[Conveyor_Weight_Tare] [decimal](18, 0) NULL,
	[Conveyor_Weight_Gross] [decimal](18, 0) NULL,
	[Conveyor_Material_Weight_Total_Net] [decimal](18, 0) NULL,
	[Conveyor_Material_Weight_Total_Tare] [decimal](18, 0) NULL,
	[Conveyor_Material_Weight_Total_Gross] [decimal](18, 0) NULL,
	[Conveyor_Material_Weight_SQM_Net] [decimal](18, 0) NULL,
	[Conveyor_Material_Weight_SQM_Tare] [decimal](18, 0) NULL,
	[Conveyor_Material_Weight_SQM_Gross] [decimal](18, 0) NULL,
	[Conveyor_Material_Flammability_LookUP] [int] NULL,
	[Conveyor_Belt_Length_MM] [int] NULL,
	[Conveyor_Belt_HorsePower_CC] [int] NULL,
	[Conveyor_Belt_Speed_Kph] [int] NULL,
	[Conveyor_Belt_Max_Kgram_Hour] [decimal](18, 0) NULL,
	[Conveyor_Belt_RPM] [int] NULL,
	[Conveyor_Belt_Weight] [decimal](18, 0) NULL,
	[Conveyor_Belt_Weight_Max_Load] [decimal](18, 0) NULL,
	[Conveyor_Power_Type] [int] NULL,
	[Conveyor_Power_Volt] [int] NULL,
	[Conveyor_Power_Ampere] [int] NULL,
	[Conveyor_Power_Ohms] [int] NULL,
	[Conveyor_Power_Siemen] [int] NULL,
	[Conveyor_Power_Polarity] [int] NULL,
	[Conveyor_Active] [bit] NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[Carrier_Conveyor] ADD  CONSTRAINT [DF_Conveyor_Details_Conveyor_Active]  DEFAULT ((0)) FOR [Conveyor_Active]