CREATE TABLE [dbo].[Security_Group](
	[Security_Group_ID] [int] IDENTITY(1,1) NOT NULL,
	[Security_Group_Name] [nchar](10) NULL,
 CONSTRAINT [PK_Security_Group] PRIMARY KEY CLUSTERED 
(
	[Security_Group_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]